(env
 (_
  (env-vars
   (ALCOTEST_COLOR auto))
  (wasm_of_ocaml
   (enabled_if %{env:WASM_OF_OCAML=false})
   (runtest_alias runtest-wasm))))

(include dune.inc)

(rule
 (targets dune.gen)
 (deps
  (source_tree .))
 (action
  (with-stdout-to
   %{targets}
   (run
    ../../gen_dune_rules.exe
    --package
    "alcotest"
    --libraries
    "alcotest.engine"
    --expect-failure
    --js
    --wasm))))

(rule
 (alias runtest)
 (package alcotest)
 (action
  (diff dune.inc dune.gen)))
