(executables
 (names simple floats)
 (modes exe js wasm)
 (libraries alcotest))

(rule
 (alias runtest)
 (package alcotest)
 (action
  (run %{dep:floats.exe})))

(rule
 (alias runtest)
 (package alcotest)
 (action
  (run %{dep:simple.exe})))

(rule
 (alias runtest-js)
 (package alcotest-js)
 (action
  (run node %{dep:floats.bc.js})))

(rule
 (alias runtest-js)
 (package alcotest-js)
 (action
  (run node %{dep:simple.bc.js})))

(rule
 (alias runtest-wasm)
 (package alcotest-wasm)
 (action
  (run node %{dep:floats.bc.wasm.js})))

(rule
 (alias runtest-wasm)
 (package alcotest-wasm)
 (action
  (run node %{dep:simple.bc.wasm.js})))
